### ISSUE TITLE
[Feature] Parse YAML Config

### ISSUE THREAD

**Issue by acavella** [acavella/gorevoke#1]
### Feature description

Ability to parse a YAML based configuration file to read user defined variables.

### Suggested implementation

Go Module: github.com/spf13/viper

Should be able to loop through an undefined number of CLR download locations.
YAML configuration should include CA ID and associated download location for each CRL at minimum.

**Comment by acavella** [comment]
Initial design completed.

Current YAML format is not satisfactory.  Will need to revisit.

Current format:
```yaml
ca:
  id:
    - x21
    - x22
  uri:
    - http://test.com
    - http://example.com
```
Preferred format:
```yaml
ca:
  - id: x21
    uri: http://test.com
  - id: x22
    uri: http://example.com
```
